### ISSUE TITLE
build error with gulp/tsc

### ISSUE THREAD

**Issue by spreakfark** [herp-app/herp-typings#1]
<img width="461" alt="grafik" src="https://user-images.githubusercontent.com/16635329/98111233-90ed3f00-1ea0-11eb-98d2-6906adc71d86.png">

i looked up this error which leads to this issue on github typescript => https://github.com/microsoft/TypeScript/issues/27956

in short: a index.d.ts is propably missing in a type package. Which is true for this repo/package too.

### how to fix
- add `index.d.ts`

**Comment by JohannesHoffmann** [comment]
the index.d.ts file should be under the dist directory

**Comment by JohannesHoffmann** [comment]
It seems that the typescript compiler needs in every directory a index.d.ts file. The dist directory creates by building. So we need an index.d.ts in src and an index.ts in src/fields.

**Comment by JohannesHoffmann** [comment]
ok this is not necessary. A configuration fail in the herp-server repo leads to the error.
[herp-app/herp-server#20](https://github.com/herp-app/herp-server/issues/20)

```
    "typeRoots": ["node_modules/@types", "node_modules/herp-typings"]
```

needs to be

```
    "typeRoots": ["node_modules/@types"]
```
